note over Client App,Client Stack,Server Stack,Server App
    Devices connected to each other. Connection parameters, MTU and PHY settings have been exchanged. The primary services have been discovered.
end note

note right of Client App
  Read characteristic
end note

Client App->>Client Stack: sl_bt_gatt_read_characteristic_value
activate Server Stack
activate Client Stack

loop Until total lenght of the characteristics has been received by chunks of (ATT_MTU-1) bytes
  note right of Client App
	Starting from 0, increment OFFSET modulo (ATT_MTU-1) bytes.
	Fore the last chunk, just use the rest modulo (ATT_MTU-1).
  end note
  Client Stack-->>Server Stack: Read Request[OFFSET]
  Server Stack->>Server App: sl_bt_evt_gatt_server_user_read_request
  note over Server App
    A transaction not completed within 30 seconds shall time out.
    Such a transaction shall be considered to have failed and
    the local higher layers shall be informed of this failure.
    For further application level communication, the devices
    will have to drop the connection and reconnect to each other.
  end note
  Server App->>Server Stack: sl_bt_gatt_server_send_user_read_response 
  Server Stack-->>Client Stack: Read Response
  Client Stack->>Client App: sl_bt_evt_gatt_characteristic_value
end

Client Stack->>Client App: sl_bt_evt_gatt_procedure_complete
